name: publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: qcastel/idhub-app:${GITHUB_REF/refs\/tags\//}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy
        uses: qcastel/github-actions-trigger-deploy@master
        with:
          git-release-bot-name: "bot-idhub"
          git-release-bot-email: "bot@idhub.io"

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_DEPLOY }}

          repository: git@github.com:idhub-io/idhub-deployment.git

          images-names: "idhub-app"



